### ISSUE TITLE
Performance issues in certain situations

### ISSUE THREAD

**Issue by Kupo91** [libretro/easyrpg-libretro#22]
#### Attach files (as a .zip archive or link them)
![rpg_rt-181028-132838](https://user-images.githubusercontent.com/41426906/47616783-acf3c400-dac1-11e8-8afd-8daa1650df56.png)
![rpg_rt-181028-143335](https://user-images.githubusercontent.com/41426906/47616788-b4b36880-dac1-11e8-800f-dae4274b65d8.png)

#### Describe the issue in detail and how to reproduce it:
I currently play Vampires Dawn and sometimes the game gets really slow. For example at entering maps with fog (screenshots). The character moves really slow then. On some maps slower than on others. Sound seems normal though. I have also laggs when certain effects appear. Not the ones in battles but on normal maps if the character is doing some sort of magic. And sometimes the character stops walking for like a second. Don't know if my hardware is too bad but I have no issues with playing PSX games and even some PSP games run without any issues so it's hard to imagine that my hardware is too bad for RPG Maker Games. I play on a TV Box with an S905X ARM chip and 2G memory.

**Comment by Ghabry** [comment]
There are performance optimisations possible for the renderer but because libretro must run on any potato they are disabled because only "newer" CPUs support them. I can document how when I finally solved the mess of a build system we have here...

For the slowdown I have working frameskip code in the queue, not ideal but it will stay at 60 FPS.

**Comment by Kupo91** [comment]
I don't know a lot about hardware and the requirements of different emu cores. Probably my TV Box is one of those potatoes too. It has only Open GL renderer. However I originally bought this box just for watching movies until I figured out that I'm able to play certain games on it aswell. Running RPG Maker games is already a success for me even if it's sometimes a bit slow.

However if I understand you right you're also working on performance issues. That sounds good. I'm looking forward to your improvements. Thanks for your effort.

**Comment by Ghabry** [comment]
Well, your ARM CPU supports ARM Neon, therefore it's not one of the potatoes I mean ;). Of course I could unconditionally enable Neon and then lets wait for crash reports.

(ARM Neon alone gives a 10-20% speedup)

**Comment by Kupo91** [comment]
Why not :P I now play the game from start to end. Good opportunity to test it

**Comment by Ghabry** [comment]
Arm Neon should be enabled now but need to wait for the buildbots to do the recompile and then figure out how to solve any build errors.

**Comment by Kupo91** [comment]
Just tried the new version and my first thought is: Amazing. It seems to be super fast now, no issues with fog anymore. However now the aspect ratio is 1:1 again :/

**Comment by Ghabry** [comment]
yes the build uses ARM Neon now, but I'm surprised that it is so much faster.

You are right, the aspect ratio commit was lost and was only on the old master branch, my fault, will fix this asap.
I also have a patch around that will support frameskipping which means even when the game lags it will still run at 60 updates per second without slowdown.

**Comment by Kupo91** [comment]
Well I just looked in the game for like a minute. In the game are some maps with those fog where the game got really slow everytime. I just entered one of them and it ran super fluent. Thats what I can say for now.
Furthermore the game got a bit choppy sometimes. Especially if it came to rain or snow on a map. Dont know if this is fixed aswell. I will play some hours when aspect ratio is normal again. Usually I have had those lags every few minutes so it wont take a lot of time to know if its better now. However it feels like entering maps is faster now too. Thanks in advance for this amazing fix :)

**Comment by Ghabry** [comment]
> However it feels like entering maps is faster now too. 

Yes because transitions are now implemented as a "drawable object" which means they will be frameskipped when not enough time is left.

**Comment by Ghabry** [comment]
Added the frameskip code, next rebuild (as usual 24 hours ;)) should fix it.

Also aspect ratio readded.

**Comment by Kupo91** [comment]
After two hours of playing thats what I can say: 
Its definitely faster. No issues with fog anymore and faster entering maps (includes battles aswell).
Lags still exist but they are a lot shorter. In the past they took like 2 seconds and now its maybe a half second. I dont know if its because enabling Neon or frame skipping. If a lag ends I'm now 3 steps farther from where I standed when the lag began. But thats okay because the shorter lags are definitely an improvement :)

**Comment by Ghabry** [comment]
hm this skipping is like on PS Vita but we don't really know the reason for it.
Does a sound effect play when the lag happens?

**Comment by Kupo91** [comment]
Yes sound is normal, he just stops walking for a short moment

**Comment by Ghabry** [comment]
could be lag because of audio loading, we have a potential solution for this but this breaks some WAV files xD

**Comment by Ghabry** [comment]
@Kupo91 
I added a patch to use our "fast wav" decoder, please try again tomorrow.

**Comment by Kupo91** [comment]
Unfortunately the patch didn't change anything for me. Maybe its not the audio but something else. If you have time and if you want to you could open the game in RPG Maker. There is one map where I have massive laggs. More than anywhere else. The name of the map is Asran. Maybe you can find there a hint about what causes those laggs?

**Comment by Kupo91** [comment]
@Ghabry Ich würd dir ja auch ne PN schreiben, um hier nicht alles voll zu spammen, aber ich kenn mich mit github nicht aus und find da nix zu xD Ich hab mich gefragt, wieso jeden Tag ein neuer easyrpg core auf buildbot gelistet wird, wenn das letzte Update 5 Tage her ist? Ich hab nämlich eben mal die neueste Version ausprobiert und bekomm da im Core eine Fehlermeldung bzgl. des Encodings.
Und wo soll ich hinschreiben, wenn mir eine Retroarchfunktion im Core fehlt? Hier nicht, wenn ich das richtig verstanden habe

**Comment by Ghabry** [comment]
> Ich würd dir ja auch ne PN schreiben, um hier nicht alles voll zu spammen, aber ich kenn mich mit github nicht aus und find da nix zu 

Github hat keine private Chatfunktion, da alle Entwickler sowieso ihren eigenen Kommunikationsweg haben. Für "normalos" ist vermutlich momentan Discord state-of-the-art, falls du mich kontaktieren willst.

> wieso jeden Tag ein neuer easyrpg core auf buildbot gelistet wird, wenn das letzte Update 5 Tage her ist

Kein Plan, ich wars nicht.

> Ich hab nämlich eben mal die neueste Version ausprobiert und bekomm da im Core eine Fehlermeldung bzgl. des Encodings.

Aber das ging schonmal vorher, oder?

Das Problem ist, dass das alles ein gigantisches gefrickel ist, mit dem ich auf dem Buildbot mein Zeug kompiliere, daher hoffe ich immer, es nie wieder anfassen zu müssen, wen es einmal geht (zumal aufm Buildbot manche Sachen die lokal gehen wiederum nicht funktionieren, alles ganz furchtbar).

> Und wo soll ich hinschreiben, wenn mir eine Retroarchfunktion im Core fehlt? Hier nicht, wenn ich das richtig verstanden habe

Kannst gern ein Issue im Bugtracker eröffnen, ich werde es aber nicht bearbeiten, da mir RetroArch vollkommen egal ist.

**Comment by Kupo91** [comment]
Ich dachte immer buildbot ist so eine Seite die die Cores sammelt und automatisch aktualisiert, sobald was geändert wurde. Deshalb war ich so irritriert, dass es in den letzten Tagen jeden Tag den easyrpg Core aktualisiert, obwohl laut github nichts verändert wurde.
Ja, die letzten beiden Cores über die wir uns noch unterhalten haben, also ohne und mit dem fast wav patch liefen noch einwandfrei. Keine Ahnung was buildbot da zusammenstellt, aber der aktuell auf buildbot verfügbare Core hat so eine Fehlermeldung am Anfang.
Ok, gut dann mach ich das mit RA und dem Bugtracker.

Edit: Achso, bevor ich es vergesse. Ich hatte neulich am Ende von VD einen Bug, der glaube ich von easyrpg ausging. Und zwar wurde bei einem Flashback der Bildschirm grau und anschließend wurde er nicht wieder farbig. Ist der Bug bekannt?

**Comment by Ghabry** [comment]
Nimmst du 32bit oder 64bit RetroArch? Probier mal die Version mit der anderen Bit-zahl.

> Achso, bevor ich es vergesse. Ich hatte neulich am Ende von VD einen Bug, der glaube ich von easyrpg ausging. Und zwar wurde bei einem Flashback der Bildschirm grau und anschließend wurde er nicht wieder farbig. Ist der Bug bekannt?

Nein, hast du einen Spielstand kurz vor dem Problem? Wäre nützlich

**Comment by Kupo91** [comment]
Weder noch glaub ich. Wenn ich nach Cores suche, dann unter armhf. Hab keine Ahnung davon, mir hat nur mal wer gesagt, dass das das Richtige für mich sei.
Savestate davon hab ich grad nicht, aber ich mach morgen eins mit dem Maker und lads dann hier hoch

**Comment by Kupo91** [comment]
Okay, also keine Ahnung, das ist sehr merkwürdig. Ich hab nun ein entsprechendes Savegame erstellt, aber ich kann den Fehler nicht mehr reproduzieren. In der Szene gibt es zwei Flashbacks, das erste beginnt, wenn man von dem Speicherpunkt einen Schritt nach rechts macht und das zweite, wenn man den Gang weiter geht. Mir ging es um das zweite Flashback, denn beim ersten war vorher alles in Ordnung, oder ich hab keinen Fehler wahrgenommen. Jetzt, als ich das Savegame testen und den Fehler reproduzieren wollte, hatte ich aber schon beim ersten einen Fehler. Nicht, dass der Bildschirm nach dem Flashback grau geblieben wäre, sondern dass die Farbe zu früh zurück kam (noch während des Flashbacks). Also quasi das Gegenteil. Dafür war bei dem zweiten Flashback aber alles in Ordnung. Und nach noch ein paar weiteren Testdurchläufen, waren beide Flashbacks in Ordnung. Den Fehler beim zweiten Flashback hatte ich mit dem easyrpg Core auf meiner TV Box. Den ersten Flashbackfehler am PC mit irgendeiner anderen easyrpg Variante. Die Leute von VD haben da so eine 64 Bit Exe erstellt, aber das basiert wohl auf easyrpg. Mehr darüber weiß ich nicht, außer dass die Fehler, die ich bisher auf meinem Core hatte, wie das Accessoires nicht richtig funktionieren, auch in der 64 Bit Variante vorhanden sind. Daher denke ich, dass das im Großen und Ganzen das Gleiche ist.
Ich hänge dir mal das Savegame an, aber ich weiß nicht, ob dir das hilft. Wie gesagt, alles sehr komisch..
[Savegame.zip](https://github.com/libretro/easyrpg-libretro/files/2639251/Savegame.zip)

**Comment by Ghabry** [comment]
Also ich weiß nicht wann auf dieser buildbot website die cores ausgetauscht werden, hab aber mal die problematische Lib ausgetauscht, vllt. ist jetzt der encoding fehler weg.

**Comment by Ghabry** [comment]
@Kupo91 
Das Problem mit "encoding" müsste jetzt gelöst sein. Evtl noch 24h warten bis alles neu gebaut wurde.

**Comment by Ghabry** [comment]
Progress update:
I reworked our Sound effect loading code.
The lag spikes when audio is loaded will be gone in Player 0.6.2. Release planned someday in April.
